name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: ansible
      url: https://github.com

    steps:
      - uses: actions/checkout@v3

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2

        with:
          playbook: playbook.yml
          directory: ./.github/ansible
          key: $SSH_KEY
          inventory: |
            [frontend]
            $USER@$HOST
