name: Production deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Get package info
        id: package
        uses: kylejrp/action-nodejs-package-info@v1.2

      - name: Check Release Existence
        id: release-existence
        uses: insightsengineering/release-existence-action@v1.0.0
        with:
          release-tag: ${{ steps.package.outputs.version }}

      - name: Create Release
        if: steps.release-existence.outputs.release-exists == 'false'
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.package.outputs.version }}
          release_name: Release ${{ steps.package.outputs.version }}
          body: |
            ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false

  build:
    runs-on: ubuntu-latest
    needs: create-release
    environment: production
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 10

      - name: Npm install
        run: npm install

      - name: Npm build
        run: npm run build:prod

      - name: Get package info
        id: package
        uses: kylejrp/action-nodejs-package-info@v1.2

      - name: Zip build folder
        run: zip -r -j front.zip dist/front/*

      - name: Upload File
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./front.zip
          tag: ${{ steps.package.outputs.version }}
          overwrite: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production
    permissions:
      contents: write
      packages: write
      pull-requests: write
      issues: write
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Get package info
        id: package
        uses: kylejrp/action-nodejs-package-info@v1.2

      - name: Deploy with ansible
        uses: dawidd6/action-ansible-playbook@v2
        env:
          ANSIBLE_HOST_KEY_CHECKING: false
        with:
          playbook: playbook.yml
          directory: ./.github/workflows/ansible
          key: ${{ secrets.SSH_KEY }}
          inventory: |
            [frontend]
            ${{ secrets.HOST }} ansible_user=${{ secrets.USER }}
          extra-vars: |
            version=${{ steps.package.outputs.version }}
            backend_host=${{ secrets.BACKEND_HOST }}
            app_path=${{ secrets.APP_PATH }}
            host=${{ secrets.HOST }}
