name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo ${{secrets.HOST}}

      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2

        with:
          playbook: playbook.yml
          directory: ./.github/ansible
          key: ${{secrets.SSH_KEY}}
          inventory: |
            [frontend]
            ${{secrets.HOST}} ansible_user=${{secrets.USER}}
